tasks:
  - name: Docker-compose
    command: cd Docker && docker-compose up -d && gp sync-done prev

  - name: iKnow-terminal
    command: gp sync-await prev && docker exec -it iknow bash -c "/home/iknow/iknow.py https://www.yelp.com/biz/social-brew-cafe-pyrmont"
    openMode: split-right
 
  - name: Bert-terminal
    command:  gp sync-await prev && docker exec -it bert /bin/bash -c "/home/bert/bert.py https://www.yelp.com/biz/social-brew-cafe-pyrmont"
    openMode: split-right
